import type { Metadata } from "next";
import LegalPage, { H2, List, SellerBlock } from "@/components/LegalPage";
import { COMPANY, DESKTOP_LICENSE, FREE_ITEM_LIMIT, PADDLE_BUYER_TERMS_URL } from "@/lib/site";

// /kullanim-sartlari sayfasının İngilizce karşılığı. Biri değişirse diğeri de aynı işte güncellenir.
export const metadata: Metadata = {
  title: "Terms of Use and Sale",
  description: "Terms for OstlerTech apps and the SyncPass Desktop Premium licence sold through Paddle.",
  alternates: { canonical: "/en/terms", languages: { tr: "/kullanim-sartlari", en: "/en/terms" } },
};

const link = "text-primary hover:text-primary-light";

export default function TermsEnPage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Use and Sale" lang="en" altLink={{ href: "/kullanim-sartlari", label: "Türkçe sürüm" }}>
      <p>
        These terms apply to the use of {COMPANY.brand} apps (SyncPass for Android, SyncPass Desktop and others) and to
        licences purchased through ostlertech.com. By using an app or purchasing a licence you accept these terms. If
        this English version and the Turkish version differ, the Turkish version prevails.
      </p>

      <H2>1. Parties</H2>
      <p>The developer of the software and licensor:</p>
      <SellerBlock lang="en" />

      <H2>2. Sales: Paddle is our Merchant of Record</H2>
      <p>
        Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all
        our orders. Paddle provides all customer service inquiries and handles returns. Payment, invoicing and taxes are
        also handled by Paddle. Your purchase is additionally subject to the{" "}
        <a href={PADDLE_BUYER_TERMS_URL} target="_blank" rel="noopener" className={link}>Paddle Buyer Terms</a>.
      </p>

      <H2>3. Product and plans</H2>
      <p>
        <strong className="text-foreground">SyncPass Desktop Premium</strong> is a licence for the SyncPass Desktop app
        (Windows 10 and 11) that removes the limits of the free version. The free version holds up to {FREE_ITEM_LIMIT}{" "}
        entries and phone sync is turned off; Premium has no entry limit and phone sync is turned on.
      </p>
      <List>
        <li><strong className="text-foreground">Monthly and yearly subscription:</strong> renews automatically at the end of the chosen period and is charged to the same payment method. The price per period is shown on the checkout page and in Paddle's e-mails.</li>
        <li><strong className="text-foreground">Lifetime:</strong> a one-time payment; it does not renew. Future updates are included.</li>
        <li>Prices are shown for your country and include applicable taxes. The price that applies is the amount shown on the checkout page when you confirm the payment.</li>
      </List>

      <H2>4. Delivery and activation</H2>
      <List>
        <li>The product is digital; nothing is shipped. When payment is complete, your licence key is shown on the page that opens after checkout; Paddle e-mails you the receipt.</li>
        <li>If you lose the key, write to {COMPANY.email} from the e-mail address you used for the purchase and we will send it again.</li>
        <li>A licence can be active on up to {DESKTOP_LICENSE.devices} computers at the same time. You can free a slot with "Remove from this computer" in the app and move to another computer.</li>
        <li>The licence is personal; it may not be sold, rented, shared or used beyond the device limit.</li>
        <li>The app checks the licence about once a week. Only the licence key, a random device ID generated by the app and the app version are sent; the contents of your vault never reach us.</li>
      </List>

      <H2>5. Cancellation and refunds</H2>
      <List>
        <li>You can cancel your subscription at any time from the link in Paddle's e-mail or at <a href="https://paddle.net" target="_blank" rel="noopener" className={link}>paddle.net</a>. Cancellation takes effect at the end of the period you have paid for; you keep Premium until then.</li>
        <li>You can request a refund for any payment within {DESKTOP_LICENSE.refundDays} days without giving a reason. Details: <a href="/en/refunds" className={link}>Refund policy</a>.</li>
      </List>

      <H2>6. When the licence ends</H2>
      <p>
        When a subscription ends or a payment is refunded, the app switches to the free version. Your vault is never
        locked: you can still view, copy, edit and export all your entries.
      </p>

      <H2>7. Master password and your data</H2>
      <p>
        SyncPass encrypts your vault on your device with a master password that only you know. Because we neither know
        nor store your master password, we cannot recover a forgotten one. Backing up your vault regularly is your
        responsibility.
      </p>

      <H2>8. Limitation of liability</H2>
      <p>
        We develop and test our apps carefully, but the software is provided "as is" and no software is entirely free of
        errors. Without prejudice to your rights under applicable consumer law, and except in cases of intent or gross
        negligence, our liability for indirect damage and data loss is limited to the licence fees you paid in the last
        12 months.
      </p>

      <H2>9. Intellectual property</H2>
      <p>
        All rights to the apps, logos and content are reserved by {COMPANY.legalName} ({COMPANY.tradeName}). The licence
        gives you the right to use the software; it gives no rights to the source code or trademarks. Licences of the
        open-source components used in the apps are listed inside the apps.
      </p>

      <H2>10. Changes and governing law</H2>
      <p>
        We may update these terms and will announce significant changes on the website. Changes do not affect, to your
        disadvantage, a period you paid for before they took effect. These terms are governed by the laws of the Republic
        of Türkiye; as a consumer you keep the mandatory consumer protection rules and remedies of your place of
        residence.
      </p>
    </LegalPage>
  );
}
