import type { Metadata } from "next";
import LegalPage, { H2, List, SellerBlock } from "@/components/LegalPage";
import { COMPANY } from "@/lib/site";

// /gizlilik sayfasının İngilizce karşılığı. Biri değişirse diğeri de aynı işte güncellenir.
export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How personal data is processed on ostlertech.com and for purchases; KVKK (Turkish data protection law) notice.",
  alternates: { canonical: "/en/privacy", languages: { tr: "/gizlilik", en: "/en/privacy" } },
};

const link = "text-primary hover:text-primary-light";

export default function PrivacyEnPage() {
  return (
    <LegalPage eyebrow="Legal" title="Privacy Policy" lang="en" altLink={{ href: "/gizlilik", label: "Türkçe sürüm" }}>
      <p>
        This notice covers the ostlertech.com website and purchases made through it. It is also our information notice
        under Türkiye's Personal Data Protection Law No. 6698 (KVKK). Our apps have their own privacy policies:{" "}
        <a href="/syncpass/privacy" className={link}>SyncPass privacy policy</a>.
      </p>

      <H2>1. Data controller</H2>
      <SellerBlock lang="en" />

      <H2>2. What data we process and why</H2>
      <List>
        <li><strong className="text-foreground">Browsing the site:</strong> we do not use cookies. To see how often pages are visited we use Vercel Web Analytics; it uses no cookies, does not identify you and counts visits through an anonymous summary that changes every day (aggregate information such as page address, country, device and browser type). Our host (Vercel) also keeps IP address and browser information in short-lived server logs for security and debugging.</li>
        <li><strong className="text-foreground">Waiting list:</strong> your e-mail address, only to tell you when a product is released.</li>
        <li><strong className="text-foreground">Purchases:</strong> our sales are made by our Merchant of Record, Paddle.com. Paddle collects your payment and billing details and processes them under its own privacy policy. Paddle sends us only your e-mail address, country, the plan you bought, transaction and subscription IDs and payment status. Purpose: delivering the licence, tracking subscription status, refunds and support.</li>
        <li><strong className="text-foreground">Licence:</strong> the licence key, a random device ID generated by the app for each activated device, the app version and the last check date. Purpose: checking that the licence is valid and the device limit. The contents of your vault never reach us.</li>
        <li><strong className="text-foreground">Support e-mails:</strong> the content of your e-mail, so that we can reply.</li>
        <li><strong className="text-foreground">Card details:</strong> Paddle takes the payment; your card number is never sent to us or stored by us.</li>
      </List>

      <H2>3. Legal grounds</H2>
      <p>
        Your data is processed on the following grounds under Article 5 of KVKK: concluding or performing a contract
        (licence, support), our legal obligations, our legitimate interest (security of the site and licences) and, for
        the waiting list, your explicit consent.
      </p>

      <H2>4. Sharing</H2>
      <p>We do not sell your data or share it for advertising. To provide the service it is shared only with these providers:</p>
      <List>
        <li>Paddle.com Market Ltd (United Kingdom): as Merchant of Record, taking payments, invoicing, taxes, subscriptions and refunds (<a href="https://www.paddle.com/legal/privacy" target="_blank" rel="noopener" className={link}>Paddle privacy policy</a>).</li>
        <li>Supabase: storing licence and waiting-list records (servers in the European Union).</li>
        <li>Vercel: hosting the site and the licence check service; anonymous visit statistics (Web Analytics).</li>
        <li>Our accountant: statutory accounting records.</li>
        <li>YouTube: only when you press play on a video on the site (via youtube-nocookie.com).</li>
        <li>Competent public authorities: only where required by law.</li>
      </List>
      <p>
        Some of these providers have servers outside Türkiye; such transfers are made in accordance with Article 9 of
        KVKK.
      </p>

      <H2>5. Retention</H2>
      <List>
        <li>Invoice records for sales are kept by Paddle; our accounting records are kept for the period required by law (10 years).</li>
        <li>Licence records: for the life of the licence and 1 year after it ends.</li>
        <li>Waiting list: deleted 6 months after the product is released, or on the day you ask to leave it.</li>
        <li>Support e-mails: 1 year after the matter is closed.</li>
        <li>Personal information in crash reports from the apps: at most 30 days.</li>
      </List>

      <H2>6. Your rights</H2>
      <p>
        Under Article 11 of KVKK you have the right to learn whether your data is processed, to request information, to
        ask for it to be corrected or deleted, to learn the third parties it was shared with, to object and to claim
        compensation for damage. You can send requests to {COMPANY.email} or to our registered e-mail (KEP) address; we
        reply within 30 days at the latest. If this English version and the Turkish version differ, the Turkish version
        prevails.
      </p>
    </LegalPage>
  );
}
